# Generated by Django 4.2.3 on 2025-04-18 16:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0020_auto_20210527_2203"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={},
        ),
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food & Groceries", "Food & Groceries"),
                    ("Books & Stationery", "Books & Stationery"),
                    ("Transportation", "Transportation"),
                    ("Entertainment", "Entertainment"),
                    ("Utilities", "Utilities"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RecurringIncome",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("content", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("weekly", "Weekly"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("content", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food & Groceries", "Food & Groceries"),
                            ("Books & Stationery", "Books & Stationery"),
                            ("Transportation", "Transportation"),
                            ("Entertainment", "Entertainment"),
                            ("Utilities", "Utilities"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("weekly", "Weekly"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
