# Generated by Django 4.2.3 on 2025-04-19 05:24

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0021_alter_expense_options_alter_budget_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\HP\\OneDrive\\Desktop\\fj\\django-expense-tracker\\media\\receipts"
                        ),
                        upload_to="receipts/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("ocr_text", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
