# Generated by Django 4.2.16 on 2025-04-22 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0023_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringincome",
            name="owner",
        ),
        migrations.DeleteModel(
            name="RecurringExpense",
        ),
        migrations.DeleteModel(
            name="RecurringIncome",
        ),
    ]
